-- 1. Create PROFILES table
create table public.profiles (
  id uuid references auth.users not null primary key,
  height numeric, -- stored in cm
  current_weight numeric, -- stored in kg
  goal_weight numeric, -- stored in kg
  weight_unit text default 'kg',
  height_unit text default 'cm',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "Users can insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

-- 2. Create ROUTINES table
create table public.routines (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  exercises jsonb default '[]'::jsonb, -- Array of exercise names
  schedule_days text[], -- Array of days e.g. ['Monday', 'Thursday']
  is_default boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for routines
alter table public.routines enable row level security;

create policy "Users can view own routines" on public.routines
  for select using (auth.uid() = user_id);

create policy "Users can insert own routines" on public.routines
  for insert with check (auth.uid() = user_id);

create policy "Users can update own routines" on public.routines
  for update using (auth.uid() = user_id);

create policy "Users can delete own routines" on public.routines
  for delete using (auth.uid() = user_id);
