-- 1. Create achievements table (lookup table)
create table if not exists public.achievements (
  id text primary key,
  name text not null,
  description text not null,
  icon_name text not null,
  requirement_type text not null, -- 'volume', 'streak', 'workout_time', 'first_workout', etc.
  requirement_value numeric not null
);

-- Enable RLS (Read-only for all authenticated users)
alter table public.achievements enable row level security;
drop policy if exists "Users can view achievements" on public.achievements;
create policy "Users can view achievements"
  on public.achievements for select
  using ( true );

-- Seed some default achievements
INSERT INTO public.achievements (id, name, description, icon_name, requirement_type, requirement_value)
VALUES 
  ('first_workout', 'First Step', 'Log your first workout.', 'Trophy', 'workouts_count', 1),
  ('1000lb_club', '1000lb Club', 'Lift a total of 1000 lbs in a single workout.', 'Dumbbell', 'workout_volume', 1000),
  ('5000lb_club', '5000lb Club', 'Lift a total of 5000 lbs in a single workout.', 'Dumbbell', 'workout_volume', 5000),
  ('3_day_streak', 'Consistency Key', 'Workout for 3 consecutive days.', 'Flame', 'streak', 3),
  ('7_day_streak', 'Unstoppable', 'Workout for 7 consecutive days.', 'Flame', 'streak', 7)
ON CONFLICT (id) DO NOTHING;

-- 2. Create user_badges table
create table if not exists public.user_badges (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  achievement_id text references public.achievements(id) not null,
  unlocked_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, achievement_id) -- User can only unlock a specific badge once
);

-- Enable RLS
alter table public.user_badges enable row level security;

drop policy if exists "Users can view their own badges" on public.user_badges;
drop policy if exists "Users can view public badges" on public.user_badges;
drop policy if exists "Users can insert their own badges" on public.user_badges;

create policy "Users can view their own badges"
  on public.user_badges for select
  using ( auth.uid() = user_id );

-- For global leaderboards, people might need to see others' badges eventually, but for now we'll allow select for all (if needed) or just own.
create policy "Users can view public badges"
  on public.user_badges for select
  using ( true );

create policy "Users can insert their own badges"
  on public.user_badges for insert
  with check ( auth.uid() = user_id );
