-- 1. Add new columns to profiles table for TDEE calculation
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS age integer;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS gender text; -- 'male' or 'female'
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS activity_level text; -- 'sedentary', 'lightly_active', 'moderately_active', 'very_active', 'super_active'
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS goal_type text; -- 'cut', 'maintain', 'bulk'

-- 2. Create nutrition_logs table
create table if not exists public.nutrition_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date date not null default current_date,
  meal_type text not null, -- 'Breakfast', 'Lunch', 'Dinner', 'Snack'
  food_text text not null, -- e.g., "2 eggs and toast"
  calories integer not null default 0,
  protein integer not null default 0,
  carbs integer not null default 0,
  fats integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.nutrition_logs enable row level security;

-- Drop existing policies if running multiple times
drop policy if exists "Users can view their own nutrition logs" on public.nutrition_logs;
drop policy if exists "Users can insert their own nutrition logs" on public.nutrition_logs;
drop policy if exists "Users can delete their own nutrition logs" on public.nutrition_logs;

-- Re-create Policies
create policy "Users can view their own nutrition logs"
  on public.nutrition_logs for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own nutrition logs"
  on public.nutrition_logs for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own nutrition logs"
  on public.nutrition_logs for delete
  using ( auth.uid() = user_id );
