-- Safely create the table if it doesn't exist
create table if not exists public.ai_reports (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  report_text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (safe to run multiple times)
alter table public.ai_reports enable row level security;

-- Drop existing policies to avoid conflicts before recreating
drop policy if exists "Users can view their own reports" on public.ai_reports;
drop policy if exists "Users can insert their own reports" on public.ai_reports;

-- Re-create Policies
create policy "Users can view their own reports"
  on public.ai_reports for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own reports"
  on public.ai_reports for insert
  with check ( auth.uid() = user_id );

-- Explicitly notify PostgREST to reload schema cache (not a standard SQL command, but creating a table usually triggers it)
comment on table public.ai_reports is 'Table for storing AI generated health reports';
